### ISSUE TITLE
Hive Session Interrupted/Closed Events from HS2

### ISSUE THREAD

**Issue by ntallapa12** [lenchv/hive-driver#30] opened 2020-04-25 12:44 UTC
Recently I created issue#20 for connection closing events in case of hive server restarts. 
I am also looking for session interrupted/closed events if there are any. 

Thank you.

**Comment by lenchv** [comment] 2020-04-26 11:30
Hi @ntallapa12 
The problem is that on the client-side there is no way to detect if a session was closed. If something goes wrong with the session (it was closed by expiration or somehow interrupted), the server returns the error as a response on request, it says smth like this: "[invalid sessionhandle <session id>](https://community.cloudera.com/t5/Support-Questions/I-got-quot-org-apache-hive-service-cli-HiveSQLException/td-p/242680)"

So to handle this you should check the error message, re-open session, and repeat request.  I am almost sure there is some unique error code for this, but I cannot exactly say which one.

**Closed** 2020-05-19 18:58 UTC
